# Generated by Django 3.2.13 on 2022-06-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_is_phone_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_phone_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
