# Generated by Django 4.0.5 on 2022-06-04 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='first_name', max_length=14)),
                ('last_name', models.CharField(blank=True, max_length=14, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', ' Others')], max_length=10)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('referral_code', models.CharField(blank=True, help_text='Don;t touch this field.This will fill automatically', max_length=40, null=True)),
                ('user_status', models.CharField(choices=[('active', 'active'), ('not-active', 'not-active'), ('suspicious', 'suspicious'), ('fraud', 'fraud')], default='active', max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
