# Generated by Django 3.2.13 on 2022-06-17 17:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/category')),
                ('status', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], max_length=10)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 6, 17, 17, 1, 33, 963380, tzinfo=utc))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keywords', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='image/subcategory')),
                ('status', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], max_length=10)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 6, 17, 17, 1, 33, 964173, tzinfo=utc))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('keywords', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'Subcategory',
                'ordering': ('-created_at',),
            },
        ),
    ]
