# Generated by Django 3.2.13 on 2022-06-19 11:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20220617_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 19, 11, 41, 5, 881752, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 19, 11, 41, 5, 882446, tzinfo=utc)),
        ),
    ]
