# Generated by Django 3.2.13 on 2022-06-23 10:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lattitude', models.CharField(blank=True, max_length=6, null=True)),
                ('longtitude', models.CharField(blank=True, max_length=6, null=True)),
                ('address', models.TextField(blank=True, max_length=200, null=True)),
                ('special_instruction', models.TextField(blank=True, max_length=150, null=True)),
                ('address_coices', models.CharField(blank=True, choices=[('Home', 'Home'), ('Office', 'Office')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 6, 23, 10, 19, 58, 487404, tzinfo=utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2022, 6, 23, 10, 19, 58, 487419, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
