# Generated by Django 3.2.13 on 2022-06-24 14:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 14, 11, 38, 839969, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='address',
            name='lattitude',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='longtitude',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 14, 11, 38, 839998, tzinfo=utc)),
        ),
    ]
