# Generated by Django 3.2.13 on 2022-06-24 14:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20220624_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 14, 13, 39, 161116, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='address',
            name='lattitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='longtitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 14, 13, 39, 161131, tzinfo=utc)),
        ),
    ]
