# Generated by Django 3.2.13 on 2022-06-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='category',
            field=models.ManyToManyField(to='category.Category'),
        ),
    ]
