# Generated by Django 3.2.13 on 2022-06-22 10:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0043_alter_products_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('expires', models.BooleanField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2022, 6, 22, 10, 38, 42, 804832, tzinfo=utc))),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.variants')),
            ],
        ),
        migrations.CreateModel(
            name='FinalCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.CharField(blank=True, max_length=40, null=True)),
                ('sub_total', models.PositiveIntegerField(default=1)),
                ('total', models.PositiveBigIntegerField(default=1)),
                ('expires', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 6, 22, 10, 38, 42, 805255, tzinfo=utc))),
                ('ordered_date', models.DateTimeField()),
                ('cart', models.ManyToManyField(to='cart.Cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
