# Generated by Django 4.0.5 on 2022-06-04 21:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0011_alter_category_created_at_alter_products_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2022, 6, 4, 21, 18, 52, 436662, tzinfo=utc))),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.variants')),
            ],
        ),
        migrations.CreateModel(
            name='FinalCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires', models.BooleanField(default=False)),
                ('coupon', models.CharField(blank=True, max_length=40, null=True)),
                ('sub_total', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 6, 4, 21, 18, 52, 437147, tzinfo=utc))),
                ('ordered_date', models.DateTimeField()),
                ('cart', models.ManyToManyField(to='cart.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
