# Generated by Django 3.2.13 on 2022-06-20 06:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_alter_products_created_at'),
        ('cart', '0023_auto_20220619_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.size'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 6, 40, 55, 84572, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='finalcart',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 6, 40, 55, 85023, tzinfo=utc)),
        ),
    ]
