# Generated by Django 3.2.13 on 2022-06-23 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('cart', '0006_auto_20220623_1619'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_charge', models.PositiveIntegerField(default=60)),
                ('order_sub_total', models.PositiveIntegerField(default=1)),
                ('order_total', models.PositiveIntegerField(default=1)),
                ('payment_method', models.CharField(max_length=20)),
                ('order_status', models.CharField(blank=True, choices=[('ceated', 'ceated'), ('confirmed', 'confirmed'), ('order_processing', 'order_processing'), ('delivery_started', 'delivery_started'), ('delivery_completed', 'delivery_completed'), ('delivery_cancelled', 'delivery_cancelled')], max_length=64, null=True)),
                ('orordered', models.BooleanField(default=False)),
                ('ordered_date', models.DateTimeField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.address')),
                ('final_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.finalcart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
