# Generated by Django 4.0.5 on 2022-06-04 17:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('products', '0002_alter_category_created_at_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 17, 33, 39, 584813, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='category',
            name='keywords',
        ),
        migrations.AddField(
            model_name='category',
            name='keywords',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 17, 33, 39, 585441, tzinfo=utc)),
        ),
    ]
