# Generated by Django 3.2.13 on 2022-06-14 06:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20220614_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='saubcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 6, 55, 55, 894790, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 6, 55, 55, 896166, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='saubcategory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 6, 55, 55, 895512, tzinfo=utc)),
        ),
    ]
