# Generated by Django 3.2.13 on 2022-06-17 17:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20220617_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 17, 3, 6, 38623, tzinfo=utc)),
        ),
    ]
