# Generated by Django 3.2.13 on 2022-06-17 17:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_alter_products_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 17, 7, 28, 780069, tzinfo=utc)),
        ),
    ]
