# Generated by Django 3.2.13 on 2022-06-19 11:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_auto_20220619_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='image_id',
        ),
        migrations.AlterField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 19, 11, 42, 32, 922723, tzinfo=utc)),
        ),
    ]
