# Generated by Django 3.2.13 on 2022-06-24 14:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_alter_products_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 14, 11, 38, 833054, tzinfo=utc)),
        ),
    ]
